[package]
name = "extract"
version = "0.1.0"
authors = ["James Elford <james.p.elford@gmail.com>"]

[dependencies]
error-chain = "0.10.0"
regex = "0.2.1"
futures = "0.1.10"

[dev-dependencies]
tempdir = "0.3.5"
